name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
